name: Build

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build2
    runs-on: self-hosted
    permissions: read-all
    steps:
      - name: Build and analyze
        env:
         shell: powershell
        run: |
          C:\Users\Sergio\.dotnet\tools\dotnet-sonarscanner begin /k:"techDebtLTIM_sonarQubeDotNet_AYuQorpj8CjBj4y8qPBq" /d:sonar.token="sqp_ec0223411c5f3dfe4d0c64fe21170118fc6d12e3" /d:sonar.host.url="http://localhost:9000"
          dotnet build
          C:\Users\Sergio\.dotnet\tools\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"