name: Main Build 

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v2  # Use actions/cache@v2 instead of @v1
        with:
          path: ~\sonar\cache  # Correct the path
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v2  # Use actions/cache@v2 instead of @v1
        with:
          path: .sonar\scanner  # Correct the path
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir .sonar\scanner  # Create the directory
          dotnet tool update dotnet-sonarscanner --tool-path .sonar\scanner  # Correct the path

      - name: Build and analyze
        run: |
          cd C:\actions-runner\_work\sonarQubeDotNet\sonarQubeDotNet
          .sonar\scanner\dotnet-sonarscanner begin /k:"SergioAVega_sonarQubeDotNet_AYuRTcoeMv0giqkxllET" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build eShopOnWeb.sln
          .sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
#      - name: JSON Report
#        run: curl.exe -u your-sonar-token:"${{ secrets.SONAR_TOKEN }}"  GET "http://localhost:9000/api/issues/search?componentKeys=SergioAVega_sonarQubeDotNet_AYuRTcoeMv0giqkxllET" -o sonarqube_report.json
